[workspace]
authors = ["benuski <ben@amongotheritems.org>"]
channels = ["conda-forge", "pytorch"]
name = "rm"
platforms = ["win-64"]
version = "0.1.0"

[dependencies]
python = "*"
pandas = ">=3.0.0,<4"
pillow = { version = ">=10.1,<11", channel = "conda-forge" }
pytorch = ">=2.7.0"
intel-openmp = "*"
cpuonly = "*"

[pypi-dependencies]
marker-pdf = ">=1.10"
