[workspace]
authors = ["benuski <ben@amongotheritems.org>"]
name = "marker-pdf-bleeding"
channels = ["conda-forge", "pytorch"]
platforms = ["win-64"]

[dependencies]
python = "*"
pandas = "*"
pillow = { version = ">=10.1,<11", channel = "conda-forge" }
transformers = { version = ">=4.45.2,<5.0.0", channel = "conda-forge" }
pytorch = ">=2.10"
torchvision = "*"

# Standard compatibility pins
libjpeg-turbo = { version = "*", channel = "conda-forge" }
numpy = { version = "<2", channel = "conda-forge" }
regex = { version = "<2025", channel = "conda-forge" }
virtualenv = ">=20.38.0,<21"
pyarrow = ">=23.0.1,<24"
beautifulsoup4 = ">=4.14.3,<5"
requests = ">=2.32.5,<3"

[pypi-dependencies]
marker-pdf = ">=1.10"
img2table = ">=1.4.2, <2"
surya-ocr = ">=0.17.1, <0.18"
pdfplumber = ">=0.11.9, <0.12"
