[workspace]
authors = ["benuski <ben@amongotheritems.org>"]
name = "marker-pdf-bleeding"
channels = ["conda-forge" "pytorch"]
platforms = ["linux-64"]

[dependencies]
python = "*"
pandas = "*"
pillow = { version = ">=10.1,<11", channel = "conda-forge" }
transformers = { version = ">=4.45.2,<5.0.0", channel = "conda-forge" }

# Standard compatibility pins
libjpeg-turbo = { version = "*", channel = "conda-forge" }
numpy = { version = "<2", channel = "conda-forge" }
regex = { version = "<2025", channel = "conda-forge" }
torch = { version = ">=2.5" }
torchvision = { version = "*" }
cpuonly = "*"

[pypi-dependencies]
marker-pdf = ">=1.10"
img2table = ">=1.4.2, <2"
surya-ocr = ">=0.17.1, <0.18"
pdfplumber = ">=0.11.9, <0.12"
